sudo: required
language: r
warnings_are_errors: false
dist: trusty

r_packages:
  - truncnorm
  - future
  - igraph
  - testthat
  - knitr

cache:
  packages: true

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test

after_success:
  - Rscript -e "covr::codecov()"

email:
  on_success: change
  on_failure: change
